# This Ansible playbook creates a new OpenStack instance
# It also creates and associates a floating IP to that instance
# We use quantum_floating_ip module to work with Neutron as nova_compute uses nova-net

- name: Create instance
  hosts: "localhost"
  gather_facts: false
  user: root
  tasks:

   - name: launch a new instance
     nova_compute:
      state: present
      login_username: userj
      login_password: Password123
      login_tenant_name: userj
      name: ansible_inst1
      auth_url: http://controller:35357/v2.0
      image_id: 47c2e674-7d25-430e-ace7-ea12b65edabf
      key_name: demo-key
      wait_for: 200
      flavor_id: 2
      nics:
       - net-id: 71ae39ba-28a0-4635-baa7-8bdc28dac1ea
      meta:
        hostname: ansible_inst1
        group: ansible_group1

   - name: attach floating IP
     quantum_floating_ip: state=present auth_url='http://controller:35357/v2.0' login_username=userj login_password=Password123 login_tenant_name=userj network_name=ext-net instance_name=ansible_inst1 internal_network_name=demo-net
